apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dummy-pdf-or-png.fullname" . }}
  labels:
    {{- include "dummy-pdf-or-png.labels" . | nindent 4 }}
spec:
  replicas: {{.Values.replicas}}
  selector:
    matchLabels:
    {{- include "dummy-pdf-or-png.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "dummy-pdf-or-png.labels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ include "dummy-pdf-or-png.fullname" . }}
          image: dummy-pdf-or-png
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          resources: 
            {{- toYaml .Values.resources | nindent 12}}
          livenessProbe:
            httpGet:
              path: /-/health
              port: http
            initialDelaySeconds: {{.Values.livenessProbe.initialDelaySeconds}}
            periodSeconds: {{.Values.livenessProbe.periodSeconds}}
          readinessProbe:
            httpGet:
              path: /-/ready
              port: http
            initialDelaySeconds: {{.Values.readinessProbe.initialDelaySeconds}}
            periodSeconds: {{.Values.readinessProbe.periodSeconds}}
