apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "dummy-pdf-or-png.fullname" . }}
  labels:
    {{- include "dummy-pdf-or-png.labels" . | nindent 4 }}
spec:
  ingressClassName:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "dummy-pdf-or-png.fullname" . }}
            port:
              number: {{.Values.service.port}}
