version: "3.4"
services:
  dummypdforpng:
    image: "dummypdforpng:latest"
    build: 
      context: ./dummy-pdf-or-png
    ports: 
      - "3000:3000"
  documentkeeper:
    image: "documentkeeper:latest"
    build: 
      context: ./DocumentKeeper
    depends_on:
      - dummypdforpng
    ports: 
      - "4096:4096"
    environment:
      - externalDNS=dummypdforpng
      - externalPort=3000
      - internalPort=4096
