apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  labels:
    app.kubernetes.io/managed-by: Helm
    httpprobecreator/probe: documentkeeper
  name: documentkeeper-probe
  namespace: default
spec:
  interval: 30s
  module: http_2xx
  prober:
    path: /read
    url: 34.116.192.232:9115 ## Using the LoadBalancer IP
  targets:
    staticConfig:
      labels:
        healthcheck: ping
        app: documentkeeper
      static:
      - http://34.118.53.100:4096/ping ## Using the service endpoint
