apiVersion: v1
kind: Service
metadata:
  name: documentkeeper
  labels:
    app: documentkeeper
spec:
  type: ClusterIP
  ports:
  - port: 4096
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: documentkeeper
