apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "document-keeper.fullname" . }}
  labels:
    {{- include "document-keeper.labels" . | nindent 4 }}
spec:
  replicas: {{.Values.replicas}}
  selector:
    matchLabels:
      {{- include "document-keeper.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "document-keeper.labels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ include "document-keeper.fullname" . }}
          image: documentkeeper
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: {{.Values.port}}
              protocol: TCP
          env:
            - name: externalDNS
              value: {{.Values.externalDNS}}
            - name: externalPort
              value: "{{.Values.externalPort}}"
            - name: internalPort
              value: "{{.Values.port}}"
          resources: 
            {{- toYaml .Values.resources | nindent 12}}
          livenessProbe:
            httpGet:
              path: /-/health
              port: http
            initialDelaySeconds: {{.Values.livenessProbe.initialDelaySeconds}}
            periodSeconds: {{.Values.livenessProbe.periodSeconds}}
          readinessProbe:
            httpGet:
              path: /-/ready
              port: http
            initialDelaySeconds: {{.Values.readinessProbe.initialDelaySeconds}}
            periodSeconds: {{.Values.readinessProbe.periodSeconds}}
