prometheus:
 prometheusSpec:
   serviceMonitorSelectorNilUsesHelmValues: false
   serviceMonitorSelector:
    matchLabels:
      app: documentkeeper
   probeSelectorNilUsesHelmValues: false
   probeSelector:
    matchLabels:
      httpprobecreator/probe: documentkeeper