apiVersion: v1
kind: Service
metadata:
  name: {{ include "document-keeper.fullname" . }}
  labels:
    {{- include "document-keeper.labels" . | nindent 4 }}
spec:
  type: {{.Values.service.type}}
  ports:
    - port: {{.Values.service.port}}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "document-keeper.selectorLabels" . | nindent 4 }}
