name: SREChallenge-CD

on:
  push:
    branches: [ "master" ]

env:
  SERVER: dummy-pdf-or-png
  PROJECT_ID: documentkeeper-04
  CLUSTER_NAME: documentkeepersre
  SERVICE: documentkeeper 
  REGION: europe-southwest1	
  REPOSITORY: images
  DEPLOYMENT_NAME: sre-test
  GKE_REGION: europe-central2-a

jobs:
  deploy:

    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCLOUD_SERVICE_KEY }}'
    
      - uses: simenandre/setup-gke-gcloud-auth-plugin@v1

      # Get the GKE credentials so we can deploy to the cluster
      - id: 'get-credentials'
        uses: 'google-github-actions/get-gke-credentials@v1'
        with:
          cluster_name: ${{ env.CLUSTER_NAME }}
          location: ${{ env.GKE_REGION }}

      - name: Helm tool installer
        uses: Azure/setup-helm@v3
        with:
          version: v3.12.3
      
      # - name: Package Helm Charts
      #   run: |
      #     helm package ./k8scharts
      #   working-directory: sre/DocumentKeeper/

      # - name: Run Helm Install
      #   run: helm install documentkeeper-1.0.0 k8scharts
      #   working-directory: sre/DocumentKeeper/
          
      # Deploy the Docker image to the GKE cluster
      - name: Deploy
        run: |-
          gcloud container clusters get-credentials $CLUSTER_NAME \
          --zone $GKE_REGION \
          --project $PROJECT_ID
          helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
          helm repo update
          helm upgrade prom prometheus-community/kube-prometheus-stack --values ./sre/DocumentKeeper/k8scharts/app/templates/prometheus.yaml
          helm upgrade bexp prometheus-community/prometheus-blackbox-exporter --values ./sre/DocumentKeeper/k8scharts/app/templates/blackbox.yaml
          kubectl apply -f ./sre/DocumentKeeper/templatesWithValues/deployment.yaml
          kubectl apply -f ./sre/DocumentKeeper/templatesWithValues/ingress.yaml
          kubectl apply -f ./sre/DocumentKeeper/templatesWithValues/service.yaml
          kubectl apply -f ./sre/DocumentKeeper/templatesWithValues/serviceMonitor.yaml
          kubectl apply -f ./sre/DocumentKeeper/templatesWithValues/probe.yaml
          kubectl apply -f ./sre/dummy-pdf-or-png/templatesWithValues/deployment.yaml
          kubectl apply -f ./sre/dummy-pdf-or-png/templatesWithValues/ingress.yaml
          kubectl apply -f ./sre/dummy-pdf-or-png/templatesWithValues/service.yaml

      ## Add this four lines to the run above in the first run of this pipeline
      ## helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
      ## helm repo update
      ## helm install prom prometheus-community/kube-prometheus-stack --values ./sre/DocumentKeeper/k8scharts/app/templates/prometheus.yaml
      ## helm install bexp prometheus-community/prometheus-blackbox-exporter --values ./sre/DocumentKeeper/k8scharts/app/templates/blackbox.yaml