name: SREChallenge-CD

on:
  push:
    branches: [ "master" ]

env:
  SERVER: dummy-pdf-or-png
  PROJECT_ID: documentkeeper-04
  CLUSTER_NAME: documentkeeper04
  SERVICE: documentkeeper 
  REGION: europe-southwest1	
  REPOSITORY: images
  DEPLOYMENT_NAME: sre-test

jobs:
  deploy:

    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCLOUD_SERVICE_KEY }}'
    
      - uses: simenandre/setup-gke-gcloud-auth-plugin@v1

      # Get the GKE credentials so we can deploy to the cluster
      - id: 'get-credentials'
        uses: 'google-github-actions/get-gke-credentials@v1'
        with:
          cluster_name: ${{ env.CLUSTER_NAME }}
          location: ${{ env.REGION }}

      # BEGIN - Docker auth and build (NOTE: If you already have a container image, these Docker steps can be omitted)

      # Authenticate Docker to Google Cloud Artifact Registry
      - name: Docker Auth
        id: docker-auth
        uses: 'docker/login-action@v1'
        with:
          username: _json_key
          password: '${{ secrets.GCLOUD_SERVICE_KEY }}'
          registry: '${{ env.REGION }}-docker.pkg.dev'

      - name: Build and Push Container DocumentKeeper
        run: |
          docker build -t "${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE }}:latest" ./sre/DocumentKeeper
          docker push "${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE }}:latest"

      - name: Build and Push Container Dummy PDF or PNG
        run: |
          docker build -t "${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVER }}:latest" ./sre/dummy-pdf-or-png
          docker push "${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVER }}:latest"
    
      # END - Docker auth and build

      - name: Helm tool installer
        uses: Azure/setup-helm@v3
        with:
          version: v3.12.3
      
      # Deploy the Docker image to the GKE cluster
      - name: Deploy
        run: |-
          gcloud container clusters get-credentials $CLUSTER_NAME \
          --zone $REGION \
          --project $PROJECT_ID
          kubectl get pods
