# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: SREChallenge-CI

on:
  push:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: documentkeeper
      PROJECT_ID: documentkeeper-04
    steps:
    - uses: actions/checkout@v3

    - name: Helm tool installer
      uses: Azure/setup-helm@v3
      with:
        version: v3.12.3

    - name: Helm Check Action
      uses: hopisaurus/helm-check-action@v0.1.1
      env:
        # Path to the values.yaml
        CHART_VALUES: sre/DocumentKeeper/k8scharts/app/values.yaml
        # Path to the Chart.yaml
        CHART_LOCATION:  sre/DocumentKeeper/k8scharts/app

    - name: Helm Check Action
      uses: hopisaurus/helm-check-action@v0.1.1
      env:
        # Path to the values.yaml
        CHART_VALUES: sre/dummy-pdf-or-png/k8scharts/app/values.yaml
        # Path to the Chart.yaml
        CHART_LOCATION:  sre/dummy-pdf-or-png/k8scharts/app

    - uses: RafikFarhad/push-to-gcr-github-action@v5-beta
      with:
        gcloud_service_key: ${{ secrets.GCLOUD_SERVICE_KEY }}
        registry: eu.gcr.io
        project_id: ${{ env.PROJECT_ID }}
        image_name: dummy-pdf-or-png
        image_tag: latest,v1
        context: ./sre/dummy-pdf-or-png

    - uses: RafikFarhad/push-to-gcr-github-action@v5-beta
      with:
        gcloud_service_key: ${{ secrets.GCLOUD_SERVICE_KEY }}
        registry: eu.gcr.io
        project_id: ${{ env.PROJECT_ID }}
        image_name: documentkeeper
        image_tag: latest,v1
        dockerfile: ./sre/DocumentKeeper/Dockerfile
        context: ./sre/DocumentKeeper
